# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91049b5ce2433e72b5fc65c14a0e7f4b30961444665ffda3c771b77b6935a2a3ca4a2dd8725179f8437d5137f6523465b02f21de9876dfe80e373a4c91cd6f25

test:
  secret_key_base: 661360ebdb098706934d44a26c27aab86c14b198127dabfbe5f7311deacde6417a959908591858bd0e1aed301056c6467f362e3130c3c63d73296e00fcd436f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
